#!/usr/bin/env node
// 聚合 themes/* → generated/themes.bundle.css
// 并注入 cf-worker-example.js 占位符：
//   @@THEMES_BUNDLE@@ / @@THEMES_BUNDLE_END@@
//   @@THEMES_RUNTIME@@ / @@THEMES_RUNTIME_END@@
import fs from "fs";
import path from "path";
import { fileURLToPath, pathToFileURL } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");
const themesDir = path.join(root, "themes");
const generatedDir = path.join(root, "generated");
const workerPath = path.join(root, "cf-worker-example.js");

function read(p) {
  return fs.readFileSync(p, "utf8");
}
function exists(p) {
  try {
    fs.accessSync(p);
    return true;
  } catch {
    return false;
  }
}

function escapeForTemplateLiteral(s) {
  return s.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}

function inject(src, startMark, endMark, payload) {
  const start = src.indexOf(startMark);
  const end = src.indexOf(endMark);
  if (start < 0 || end < 0 || end < start) {
    console.error("[build-themes] placeholder not found:", startMark);
    process.exit(1);
  }
  return (
    src.slice(0, start) +
    startMark +
    "\n" +
    payload +
    "\n" +
    endMark +
    src.slice(end + endMark.length)
  );
}

const manifestPath = path.join(themesDir, "manifest.js");
const mod = await import(pathToFileURL(manifestPath).href);
const { THEMES, THEME_ALIAS, DEFAULT_THEME_ID } = mod;

const parts = [];
parts.push("/* generated by scripts/build-themes.mjs — do not edit by hand */");
parts.push(read(path.join(themesDir, "base.css")));

for (const t of THEMES) {
  const tokenPath = path.join(themesDir, t.file || `tokens/${t.id}.css`);
  if (!exists(tokenPath)) {
    console.error("[build-themes] missing token:", tokenPath);
    process.exit(1);
  }
  parts.push(read(tokenPath));
  if (t.overrides) {
    const op = path.join(themesDir, t.overrides);
    if (exists(op)) {
      const body = read(op).trim();
      if (body.includes("{")) parts.push(read(op));
    }
  }
}

// optional cyber overrides if present
const cyberOv = path.join(themesDir, "overrides", "cyber.css");
if (exists(cyberOv)) {
  const body = read(cyberOv).trim();
  if (body.includes("{") && !THEMES.some((t) => t.overrides === "overrides/cyber.css")) {
    parts.push(body);
  }
}

const sw = path.join(themesDir, "swatches.css");
if (exists(sw)) parts.push(read(sw));

const bundle = parts.join("\n\n").replace(/\n{3,}/g, "\n\n") + "\n";
fs.mkdirSync(generatedDir, { recursive: true });
const bundlePath = path.join(generatedDir, "themes.bundle.css");
fs.writeFileSync(bundlePath, bundle, "utf8");
console.log("[build-themes] wrote", path.relative(root, bundlePath), `(${bundle.length} bytes)`);

const runtime =
  "const THEMES = " +
  JSON.stringify(
    THEMES.map(({ id, name, desc }) => ({ id, name, desc })),
    null,
    2
  ) +
  ";\nconst THEME_ALIAS = " +
  JSON.stringify(THEME_ALIAS, null, 2) +
  ";\nconst DEFAULT_THEME_ID = " +
  JSON.stringify(DEFAULT_THEME_ID) +
  ";\n";

const runtimePath = path.join(generatedDir, "themes.runtime.js");
fs.writeFileSync(runtimePath, runtime, "utf8");
console.log("[build-themes] wrote", path.relative(root, runtimePath));

if (!exists(workerPath)) {
  console.error("[build-themes] worker not found:", workerPath);
  process.exit(1);
}

let worker = read(workerPath);
worker = inject(
  worker,
  "/* @@THEMES_BUNDLE@@ */",
  "/* @@THEMES_BUNDLE_END@@ */",
  escapeForTemplateLiteral(bundle)
);
worker = inject(
  worker,
  "/* @@THEMES_RUNTIME@@ */",
  "/* @@THEMES_RUNTIME_END@@ */",
  escapeForTemplateLiteral(runtime)
);
fs.writeFileSync(workerPath, worker, "utf8");
console.log("[build-themes] injected into", path.relative(root, workerPath));
