name: Deploy to Cloudflare Workers

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4

      - name: Replace D1 database_id
        run: |
          sed -i "s/{CLOUDFLARE_D1_ID}/${CLOUDFLARE_D1_ID}/g" wrangler.toml
        env:
          CLOUDFLARE_D1_ID: ${{ secrets.CLOUDFLARE_D1_ID }}

      - name: Deploy Worker
        uses: cloudflare/wrangler-action@v4.0.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy
          wranglerVersion: "3.109.0"